venv_help_child/help_child/help_child/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('accounts/password_change_form/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change_form'),    # 追加
    path('accounts/password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_finish.html'), name='password_change_done'), # 追加
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_help_child/help_child/main/urls.py
from django.urls import path
from . import views


app_name="main"

urlpatterns=[
    path('',views.HomeView.as_view(),name="home"),
    # path('login',views.LoginView.as_view(),name="login"),
    path('locationAdmin',views.LocationAdminView.as_view(),name="locationAdmin"),
    path('locationParent',views.LocationParentView.as_view(),name="locationParent"),
    path('locationConfig',views.LocationConfigView.as_view(),name="locationConfig"),

    path('contactTop',views.ContactTopView.as_view(),name="contactTop"),
    path('contactTop_oya',views.ContactTopOyaView.as_view(),name="contactTop_oya"),
    path('contactDetail',views.ContactDetailView.as_view(), name="contactDetail"),
    path('contactUpdate',views.ContactUpdateView.as_view(), name="contactUpdate"),
    path('contactUpdate_oya/<str:pk>/',views.ContactUpdateOyaView.as_view(), name="contactUpdate_oya"),
    path('contactTemplate',views.ContactTemplateView.as_view(),name="contactTemplate"),

    path('attend',views.AttendView.as_view(),name="attend"),

    path('planList',views.PlanListView.as_view(),name="planList"),
    path('planListAdd',views.PlanListAddView.as_view(),name="planListAdd"),
    path('planListDetail',views.PlanListDetailView.as_view(),name="planListDetail"),
    path('planListUpdate',views.PlanListUpdateView.as_view(),name="planListUpdate"),
    path('planListDelete',views.PlanListDeleteView.as_view(),name="planListDelete"),

    path('blogDetail',views.BlogDetailView.as_view(),name="blogDetail"),
    path('blogCreate',views.BlogCreateView.as_view(),name="blogCreate"),
    path('blogUpdate/<int:pk>/',views.BlogUpdateView.as_view(),name="blogUpdate"),
    path('blogDelete/<int:pk>/',views.BlogDeleteView.as_view(),name="blogDelete"),

    path('childrenlistTop',views.ChildrenListTopView.as_view(),name='childrenlistTop'),
    path('childminderlistTop',views.ChildminderListTopView.as_view(),name='childminderlistTop'),
    path('parentslistTop',views.ParentsListTopView.as_view(),name='parentslistTop'),
    path('chilrenDetail',views.ChildrenDetailView.as_view(),name="childrenDetail"),
    path('childminderDetail',views.ChildminderDetailView.as_view(),name="childminderDetail"),
    path('parentsDetail',views.ParentsDetailView.as_view(),name="parentsDetail"),
    path('childrenUpdate/<pk>/',views.ChildrenUpdateView.as_view(),name="childrenUpdate"),
    path('childminderUpdate/<pk>/',views.ChildminderUpdateView.as_view(),name="childminderUpdate"),
    path('childminder2Update/<pk>/',views.Childminder2UpdateView.as_view(),name="childminder2Update"),
    path('parentsUpdate/<pk>/',views.ParentsUpdateView.as_view(),name="parentsUpdate"),
    path('childrenDelete/<pk>/',views.ChildrenDeleteView.as_view(),name="childrenDelete"),
    path('childminderDelete/<pk>/',views.ChildminderDeleteView.as_view(),name="childminderDelete"),
    path('parentsDelete/<pk>/',views.ParentsDeleteView.as_view(),name="parentsDelete"),
    path('childrenCreate',views.ChildrenCreateView.as_view(),name="childrenCreate"),
    path('childminderCreate',views.ChildminderCreateView.as_view(),name="childminderCreate"),
    path('childminder2Create',views.Childminder2CreateView.as_view(),name="childminder2Create"),
    path('parentsCreate',views.ParentsCreateView.as_view(),name="parentsCreate"),
    path('parents2Create',views.Parents2CreateView.as_view(),name="parents2Create"),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),  
    path('password_change_done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'), 

    path('classCreate',views.ClassCreateView.as_view(),name="classCreate"),

]

venv_help_child/help_child/main/views.py
from audioop import reverse
import email
from json.tool import main
from pyexpat.errors import messages
from django.core.mail import message
from django.contrib import messages as add_messages
from django.http import request
from django.shortcuts import render
from django.template import context
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from accounts.models import *
from main.models import *
# Create your views h
from .models import *
from django.db.models import Q, F
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from django.db import transaction
import logging
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


from datetime import time
logger = logging.getLogger('development')


class BaseView(generic.TemplateView):
    template_name = "base.html"


class HomeView(LoginRequiredMixin, generic.TemplateView):
    model = T013Blog,T008Schedule
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        blog = super().get_context_data(**kwargs)
        schedule = super().get_context_data(**kwargs)
        blog["object_list"] = T013Blog.objects.order_by(
            '-t013_fd06_createdata')
        one_week = datetime.datetime.now() + datetime.timedelta(days = 7)
        schedule["object"] = T008Schedule.objects.filter(t008_fd03_date__range=[datetime.datetime.now(),one_week,])
        return blog

# class LoginView(generic.TemplateView):
#     template_name="login.html"


class LocationAdminView(LoginRequiredMixin, generic.TemplateView):
    template_name = "locationAdmin.html"


class LocationParentView(LoginRequiredMixin, generic.TemplateView):
    template_name = "locationParent.html"


class LocationConfigView(LoginRequiredMixin, generic.TemplateView):
    template_name = "locationConfig.html"


class ContactTopView(generic.ListView, LoginRequiredMixin):

    template_name = "ContactTop.html"
    model = T001Children

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ユーザ種類別のデータの取り出し方...self.request.user.detail_buyer←ここでrelated_nameを指定する！！！！！！！！！！！！！！！
        context["contact"] = T001Children.objects.filter(
            t001_fk01_class_id=self.request.user.detail_buyer.class_id)
        return context

    def get_queryset(self):
        contact = T001Children.objects.all().select_related()
        # 検索box 絞り込み
        if "query" in self.request.GET:
            search = self.request.GET["query"]
            or_lookup = (
                Q(t001_fd08_last_name_kana__icontains=search)|
                Q(t001_fd09_first_name_kana__icontains=search) |
                Q(t001_fd01_last_name__icontains=search) |
                Q(t001_fd07_first_name__icontains=search) 
            )
            contact = contact.filter(or_lookup)
        return contact


class ContactTopOyaView(LoginRequiredMixin, generic.TemplateView):
    template_name = "contactTop_oya.html"
    model = T001Children

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = T001Children.objects.filter(
            t001_fk02_parents_id=self.request.user.detail_supplier.id)
        return context


class ContactDetailView(LoginRequiredMixin, generic.TemplateView):
    template_name = "contactDetail.html"
    context_object_name = 'object'
    model = CustomUser

    def get_context_data(self, **kwargs):
        renrakucho = super().get_context_data(**kwargs)
        id = self.request.GET.get("id", "01")
        num = self.request.GET.get("num", "20211201")
        renrakucho["object"] = T007Contactbook.objects.filter(
            t007_fd01_date=datetime.datetime.strptime(num, '%Y%m%d'), t007_fk01_children_id=id)
        return renrakucho

    def get_queryset(self):
        return CustomUser.objects.filter(username=self.request.user.username)


class ContactUpdateView(LoginRequiredMixin, generic.CreateView):
    model = T007Contactbook
    template_name = "contactUpdate.html"
    form_class = SchoolContactForm
    success_url = reverse_lazy('main:contactTop')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num = self.request.GET.get("num", "20211201")
        id = self.request.GET.get("id", "01")
        a=T012Contactbooktem.objects.all().first()
        
        initial_dict = {
        't007_fk01_children_id': id,
        't007_pk01_contactbook_id': num+id,
        't007_fd15_lunch_contents': a.t012_fd04_meal_contents,
        't007_fd16_lunch_time':datetime.time(a.t012_fd03_mealtime.hour,a.t012_fd03_mealtime.minute),
        't007_fd27_bed_time':a.t012_fd05_bed_time,
        't007_fd17_wakeup_time':a.t012_fd06_wakeup_time,
        't007_fd24_infomation':a.t012_fd02_information
        }
        
        context['form'] = SchoolContactForm(self.request.POST or None, initial=initial_dict)
        # test
        return context

    def form_valid(self, form):
        main = form.save(commit=False)
        main.user = self.request.user
        main.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class ContactUpdateOyaView(LoginRequiredMixin, generic.UpdateView):

    model = T007Contactbook
    template_name = "contactUpdate_oya.html"
    form_class = HomeContactForm
    success_url = reverse_lazy('main:contactTop_oya')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        num = self.kwargs.get('pk')
        default_data = {
            't007_pk01_contactbook_id': num,
            't007_fk01_children_id': num[8:]
        }
        homecontact_form = HomeContactForm(initial = default_data)
        context['form'] = homecontact_form

        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class ContactTemplateView(LoginRequiredMixin, generic.CreateView):
    model = T012Contactbooktem
    fields = '__all__'
    template_name = "contactTemplate.html"

    def post(self, request, *args, **kwargs):
        if self.request.POST.getlist('data', None):
            post = self.request.POST.getlist('data', None)
            a=T003Childminder.objects.get(user__username=self.request.user.username)
            T012Contactbooktem.objects.create(t012_fd03_mealtime=post[0], t012_fd04_meal_contents=post[1],
                                            t012_fd05_bed_time=post[2], t012_fd06_wakeup_time=post[3], t012_fd02_information=post[4],t012_fk01_childminder_id=a)
        return self.get(request, *args, **kwargs,)


class MessageAddressView(LoginRequiredMixin, generic.ListView):
    template_name = "messageAddress.html"


class MessageView(LoginRequiredMixin, generic.TemplateView):
    template_name = "message.html"


class AttendView(LoginRequiredMixin, generic.ListView):
    model = T001Children
    template_name = "attend.html"

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('update_button', None):
            t = T001Children.objects.filter(
                t001_pk01_children_id=self.request.POST.get('update_button')).first()
            t.t001_fd11_kindergaten = not bool(t.t001_fd11_kindergaten)
            t.save()
        elif self.request.POST.get('all_true_button', None):
            T001Children.objects.filter(t001_fk01_class_id=self.request.user.detail_buyer.class_id).update(
                t001_fd11_kindergaten=True)
        elif self.request.POST.get('all_false_button', None):
            T001Children.objects.filter(t001_fk01_class_id=self.request.user.detail_buyer.class_id).update(
                t001_fd11_kindergaten=False)
        return self.get(request, *args, **kwargs,)

    def get_queryset(self):
        toukouenn = T001Children.objects.filter(
            t001_fk01_class_id=self.request.user.detail_buyer.class_id).select_related()
        # 検索box 絞り込み
        # if "query" in self.request.GET:
        #    search = self.request.GET["query"]
        #    or_lookup = (
        #        Q(t005_pk01_childen_id__icontains=search)
        #    )
        #    toukouenn = toukouenn.filter(or_lookup)

        return toukouenn


# 名簿画面は作らないことになった
# class NameListView(generic.TemplateView):
#     template_name="nameList.html"

# class NameListDetailView(generic.TemplateView):
#     template_name="nameListDetail.html"

# class NameListAddView(generic.TemplateView):
#     template_name="nameListAdd.html"

# class NameListUpdateView(generic.TemplateView):
#     template_name="nameListUpdate.html"


class PlanListView(LoginRequiredMixin, generic.TemplateView):
    template_name = "planlist.html"


class PlanListDetailView(LoginRequiredMixin, ListView):
    template_name = "planListDetail.html"
    paginate_by = 2
    paginate_orphans = 1
    context_object_name = "object"

    model = T008Schedule

    # def get_context_data(self, **kwargs):
    #     planListdetail = super().get_context_data(**kwargs)
    #     num = self.request.GET.get("num", "20211207")
    #     planListdetail["object"] = T008Schedule.objects.filter(
    #         t008_fd03_date=datetime.datetime.strptime(num, '%Y%m%d'))
    #     return planListdetail

    def get_queryset(self):
        planListdetail = T008Schedule.objects.all()
        num = self.request.GET['num']
        if num is not None:
            planListdetail = T008Schedule.objects.filter(
                t008_fd03_date=datetime.datetime.strptime(num, '%Y%m%d'))
        return planListdetail


class PlanListAddView(LoginRequiredMixin, generic.TemplateView):
    template_name = "planListAdd.html"
    context_object_name = "objects"
    model=T004Class

    def post(self, request, *args, **kwargs):

venv_help_child/help_child/main/templates/base.html
{% load static %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ここにサイト説明を入れます">
    <meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amatic+SC:700">
    <link rel="shortcut icon" href="{% static 'images/CHILink.jpg' %}">
    <script type="text/javascript" src="{% static 'js/openclose.js' %}"></script>

    <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
    {% block head %}{% endblock %}
</head>

<!--小さな端末用（800px以下端末）メニュー-->
<nav id="menubar-s">
    <ul id="menu-list">
        <h1>機能一覧</h1>
        {% if user.detail_buyer %}
        <li><a href="{% url 'main:contactTop' %}" style="width: 100%;">連絡帳<span>Contact</span></a></li>
        {% else %}
        <li><a href="{% url 'main:contactTop_oya' %}" style="width: 100%;">連絡帳<span>Contact</span></a></li>
        {% endif %}
        <li><a href="{% url 'main:planList' %}" style="width: 100%;">予定表<span>PlanList</span></a></li>
        <li><a href="{% url 'main:locationAdmin' %}" style="width: 100%;">位置情報<span>Location</span></a></li>
        {% if user.detail_buyer %}
        <li><a href="{% url 'main:attend' %}" style="width: 100%;">登園管理<span>Attend</span></a></li>
        <li><a href="{% url 'main:childrenlistTop' %}" style="width: 100%;">名簿<span>Enji</span></a></li>
        {% endif %}
    </ul>
</nav>

<body id="top">
    <!--上部の装飾画像-->
    {% block head_slide %}{% endblock %}
    <div id="container">

        <!--小さな端末用（800px以下端末）ロゴ-->
        <h1 id="logo-s"><a href="{% url 'main:home' %}"><img src="{% static 'images/CHILink.jpg' %}"
                    alt="SAMPLE KIDS CLUB"></a></h1>

        <div id="contents">

            {% block main_contents%}{% endblock %}

            <div id="sub">

                <!--大きな端末用（801px以上端末）ロゴ-->
                <h1 id="logo"><a href="{% url 'main:home'%}"><img src="{% static 'images/CHILink.jpg' %}"
                            alt="SAMPLE KIDS CLUB"></a>
                </h1>
                <!--大きな端末用（801px以上端末）メニュー-->
                <nav id="menubar">

                    <ul class="mb30">
                        {% if user.detail_buyer %}
                        <li><a href="{% url 'main:contactTop' %}">連絡帳<span>Contact</span></a></li>
                        {% else %}
                        <li><a href="{% url 'main:contactTop_oya' %}">連絡帳<span>Contact</span></a></li>
                        {% endif %}
                        <li><a href="{% url 'main:planList' %}">予定表<span>PlanList</span></a></li>
                        <!-- <li><a href="{% url 'main:locationAdmin' %}">位置情報<span>Location</span></a></li> -->
                        {% if user.detail_buyer %}
                        <li><a href="{% url 'main:attend' %}">登園管理<span>Attend</span></a></li>
                        <li><a href="{% url 'main:childrenlistTop' %}">名簿<span>Enji</span></a></li>
                        {% endif %}
                    </ul>
                </nav>

                <nav class="box2">
                    <h2>ユーザー情報</h2>
                    <ul class="usermenu">
                        <img src="{% static 'images/profile_icon.png' %}">
                        <a href="{%url 'main:childminderDetail'%}?Email={{user.email}}">
                            {{user.get_full_name}}<br>
                        </a>
                        <li><a href="/accounts/logout">ログアウト</a></li>
                        <li><a href="{% url 'password_change_form' %}">パスワード変更</a></li>
                    </ul>
                </nav>
                {% block sub_contents%}

            </div>
            {% endblock %}
            <!--/sub-->

            <p id="pagetop"><a href="#"><img src="{% static 'images/pagetop.png' %}" alt="ページの上部へ"></a></p>

        </div>

        {% block contents%}{% endblock %}
        <!--/contents-->

        <footer>
            <small>Copyright&copy; <a href="base.html">SAMPLE KIDS CLUB</a> All Rights Reserved.</small>
            <span class="pr"><a href="http://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
        </footer>

    </div>
    <!--/container-->

    {% block animation %}{% endblock %}

    <!--メニューの３本バー-->
    <div id="menubar_hdr" class="close">
        <a class="menu-btn">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>

    <div id="return-btn">
        <a href="#" onclick="history.back(-1);return false;">↩</a>
    </div>

    <!--メニューの開閉処理条件設定　800px以下-->
    <script type="text/javascript">
        if (OCwindowWidth() <= 800) {
            open_close("menubar_hdr", "menubar-s");
        }
    </script>
</body>

</html>

venv_help_child/help_child/main/templates/parentslistTop.html
{% extends 'base.html' %}
{% load static %}
<!--連絡帳園児リスト画面-->
{% block head %}
<link rel="stylesheet" href="{% static 'css/sugahara.css' %}">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" src="{% static 'js/matsuoka.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
{% endblock %}

{% block title %}連絡帳園児リスト-CONTACT{% endblock %}

{% block head_slide%}
<!--スライドショー-->
<aside id="mainimg">
    <div>
        <img src="{% static 'images/0.png' %}" alt="" id="slide0">
        <img src="{% static 'images/1.jpg' %}" alt="" id="slide1">
        <img src="{% static 'images/2.jpg' %}" alt="" id="slide2">
        <img src="{% static 'images/3.jpg' %}" alt="" id="slide3">
    </div>
</aside>
{% endblock %}

{% block main_contents%}
<div class="contact-top-main">
    <h2>保護者名簿</h2>
    <div class="list-select">
        <a href="{% url 'main:childrenlistTop' %}" id="child-select-btn-p">園　児</a>
        <a href="{% url 'main:parentslistTop' %}" id="parent-select-btn-p">保護者</a>
        <a href="{% url 'main:childminderlistTop' %}" id="minder-select-btn-p">保育士</a>
    </div>
    <!-- 園児年齢別選択 -->

    <!-- 検索ボックス Django-->
    <form action="" method="get" class="search_container">
        <input name="query" value="{{ request.GET.query }}" type="text" id="search-text" onkeyup="myFunction()"
            size="30" placeholder="名前検索(ひらがな)">
    </form>

    <!-- リスト -->
    <ul class="child-list">

        <table border="2" style="border-collapse: collapse; border-color: #000">
            <tr>
                <th class="class-name">
                    名前
                </th>
                <th class="child-name">
                    よみがな(姓名)
                </th>
            </tr>
            
             {% for iiii in object_list %}
            <tr>
                <td class="class-name">
                    <li class="list_item" data-hobby="age4">
                        <p>{{ iiii.user.get_full_name }}</p>
                    </li>
                </td>
                <td class="child-name">
                    <li class=" list_item" data-hobby="age4">
                        <p>{{ iiii.user.get_full_name_kana }}</p>
                    </li>
                </td>
                <td class="select">
                    <a href="{%url 'main:parentsDetail'%}?Email={{iiii.user.email}} " class="select-btn">詳細</a>
                    <a href="{%url 'main:parentsUpdate' iiii.user.email %}" class=" select-btn">編集</a>
                    <a href="{%url 'main:parentsDelete' iiii.user.email %}" class="select-btn">削除</a>
                </td>
            </tr>
            {% empty %}
            {% endfor %}
        </table>
        <a href="{%url 'main:parentsCreate' %}" class="select-btn">作成</a>
    </ul>
</div>
{% endblock %}

{% block sub_contents%}
<!-- 関連項目 -->
<!-- <nav class=" box1">
    <h2>連絡帳関連</h2>
    <ul class="submenu">

        <li><a href="{% url 'main:childrenlistTop' %}">園児</a></li>
        <li><a href="{% url 'main:childminderlistTop' %} ">保育士</a></li>
        <li><a href="{% url 'main:classCreate' %} ">クラス作成</a></li>
    </ul>
</nav> -->
{% endblock %}

venv_help_child/help_child/main/templates/planListDelete.html
{%extends 'base.html'%}
{%load static %}
{% block head %}

<meta charset="utf-8">
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/sugahara.js' %}"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<link rel="stylesheet" href="{% static 'css/suda.css' %}">

<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<script type="text/javascript" src="{% static 'js/planlistDetail.js' %}"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/cupertino/jquery-ui.css">

{% endblock %}

{% block head_slide%}

<!--スライドショー-->

<aside id="mainimg">
    <div>
        <img src="{% static 'images/0.png' %}" alt="" id="slide0">
        <img src="{% static 'images/1.jpg' %}" alt="" id="slide1">
        <img src="{% static 'images/2.jpg' %}" alt="" id="slide2">
        <img src="{% static 'images/3.jpg' %}" alt="" id="slide3">
    </div>
</aside>

{% endblock %}

{% block main_contents%}
<div id="plmain">
    <div id="header">
        <!-- <div id="attend-main"> -->
        <h2>予定表削除</h2>
        <div class="group">
            <div class="head">
                <div class="title">年齢：</div>
                <div class="checkAll">
                    <label class="label">
                        <input class="js-check-all" type="checkbox" name="" data-check-all="hobby">
                        <span class="text">All</span>
                    </label>
                </div>
            </div>
            <ul class="js-check-all-target list" data-check-all="hobby">
                <li class="item">
                    <label class="label">
                        <input type="checkbox" name="hobby" value="age0">
                        <span class="text">0歳児</span>
                    </label>
                </li>
                <li class="item">
                    <label class="label">
                        <input type="checkbox" name="hobby" value="age1">
                        <span class="text">1歳児</span>
                    </label>
                </li>
                <li class="item">
                    <label class="label">
                        <input type="checkbox" name="hobby" value="age2">
                        <span class="text">2歳児</span>
                    </label>
                </li>
                <li class="item">
                    <label class="label">
                        <input type="checkbox" name="hobby" value="age3">
                        <span class="text">3歳児</span>
                    </label>
                </li>
                <li class="item">
                    <label class="label">
                        <input type="checkbox" name="hobby" value="age4">
                        <span class="text">4歳児</span>
                    </label>
                </li>
                <li class="item">
                    <label class="label">
                        <input type="checkbox" name="hobby" value="age5">
                        <span class="text">5歳児</span>
                    </label>
                </li>
            </ul>
        </div>
    </div>

    <form action="window.alert(target)" method="post" class="planlistDetailCenter">
        <h4>日 付 : <input type="text" placeholder="日付検索" id="target" text-align="center"></h4>
        <h4>行事名 : <select name="planName">
                <option value="サンプル1">１２３４５６７８９０１２３４５</option>
                <!--最大表示14文字-->
                <option value="サンプル2">サンプル2</option>
                <option value="サンプル3">サンプル3</option>
            </select></h4>
        <br>
        <input type="submit" value="削除" class="planlistAddButton">
    </form>
</div>


<!--予定の表示-->

{%endblock%}

{% block sub_contents%}
<nav class="box1">
    <h2>予定表関連</h2>
    <ul class="submenu">

        <li><a href="{% url 'main:planList' %}">カレンダー</a></li>
        <!-- <li><a href="#">詳細</a></li> -->
        <li><a href="{% url 'main:planListAdd' %}">行事の追加</a></li>
        <!-- <li><a href="{% url 'main:planListUpdate' %}">編集</a></li> -->
    </ul>
</nav>
{% endblock %}

</html>